/// Generates `lib/src/layout/line_break_data.g.dart` from the Unicode
/// Character Database files in `vendor/unicode` (Unicode 18.0.0): the
/// Line_Break class of every code point, merged with the other properties
/// the rules of UAX #14 look at (East_Asian_Width F, W or H; the
/// General_Category Pi and Pf; Extended_Pictographic code points that are
/// unassigned), as a table of ranges.
///
/// ```sh
/// dart run tool/generate_line_break.dart
/// ```
library;

import 'dart:io';
import 'dart:typed_data';

/// The Line_Break classes, in the order of `LineBreakClass` in
/// `lib/src/layout/line_break.dart`.
const List<String> classes = [
  'BK', 'CR', 'LF', 'CM', 'NL', 'SG', 'WJ', 'ZW', 'GL', 'SP', 'ZWJ', //
  'B2', 'BA', 'BB', 'HY', 'CB', 'CL', 'CP', 'EX', 'IN', 'NS', 'OP', 'QU',
  'IS', 'NU', 'PO', 'PR', 'SY', 'AI', 'AK', 'AL', 'AP', 'AS', 'CJ', 'EB',
  'EM', 'H2', 'H3', 'HH', 'HL', 'ID', 'JL', 'JV', 'JT', 'RI', 'SA', 'VF',
  'VI', 'XX',
];

const int eastAsian = 1 << 6;
const int initialPunctuation = 1 << 7;
const int finalPunctuation = 1 << 8;
const int unassignedPictographic = 1 << 9;
const int combiningMark = 1 << 10; // General_Category Mn or Mc

void main() {
  final root = File(Platform.script.toFilePath()).parent.parent.path;
  final values = Uint16List(0x110000);
  final xx = classes.indexOf('XX');
  values.fillRange(0, values.length, xx);

  void each(String file, void Function(int start, int end, String value) f) {
    for (final line in File('$root/vendor/unicode/$file').readAsLinesSync()) {
      final data = line.split('#').first.trim();
      if (data.isEmpty) continue;
      final [range, value] = data.split(';').map((s) => s.trim()).toList();
      final bounds = range.split('..');
      final start = int.parse(bounds.first, radix: 16);
      final end = int.parse(bounds.last, radix: 16);
      f(start, end, value);
    }
  }

  each('LineBreak.txt', (start, end, value) {
    final index = classes.indexOf(value);
    if (index < 0) throw StateError('unknown Line_Break class $value');
    for (var c = start; c <= end; c++) {
      values[c] = index;
    }
  });
  each('EastAsianWidth.txt', (start, end, value) {
    if (value == 'F' || value == 'W' || value == 'H') {
      for (var c = start; c <= end; c++) {
        values[c] |= eastAsian;
      }
    }
  });
  final unassigned = List<bool>.filled(0x110000, false);
  each('DerivedGeneralCategory.txt', (start, end, value) {
    final flag = switch (value) {
      'Pi' => initialPunctuation,
      'Pf' => finalPunctuation,
      'Mn' || 'Mc' => combiningMark,
      _ => 0,
    };
    for (var c = start; c <= end; c++) {
      values[c] |= flag;
      if (value == 'Cn') unassigned[c] = true;
    }
  });
  each('emoji-data.txt', (start, end, value) {
    if (value != 'Extended_Pictographic') return;
    for (var c = start; c <= end; c++) {
      if (unassigned[c]) values[c] |= unassignedPictographic;
    }
  });

  final starts = <int>[];
  final rangeValues = <int>[];
  for (var c = 0; c < values.length; c++) {
    if (c == 0 || values[c] != values[c - 1]) {
      starts.add(c);
      rangeValues.add(values[c]);
    }
  }
  final version = RegExp(r'LineBreak-([\d.]+)\.txt')
      .firstMatch(
        File('$root/vendor/unicode/LineBreak.txt').readAsStringSync(),
      )!
      .group(1);
  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln('// Generated by `dart run tool/generate_line_break.dart` from')
    ..writeln('// the Unicode Character Database $version (vendor/unicode;')
    ..writeln('// see vendor/unicode/license.txt for its terms).')
    ..writeln()
    ..writeln('/// The line breaking properties of every code point.')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// The Unicode version of the data.')
    ..writeln("const String unicodeVersion = '$version';")
    ..writeln()
    ..writeln('/// The first code point of each range of code points with the')
    ..writeln('/// same properties.')
    ..writeln('const List<int> rangeStarts = [')
    ..writeln(_wrap(starts))
    ..writeln('];')
    ..writeln()
    ..writeln('/// The properties of each range: the Line_Break class (low six')
    ..writeln('/// bits) and the flags of `line_break.dart`.')
    ..writeln('const List<int> rangeValues = [')
    ..writeln(_wrap(rangeValues))
    ..writeln('];');
  File('$root/lib/src/layout/line_break_data.g.dart')
      .writeAsStringSync(out.toString());
  stdout.writeln('generate_line_break: ${starts.length} ranges');
}

String _wrap(List<int> values) {
  final lines = <String>[];
  var line = StringBuffer('  ');
  for (final value in values) {
    final item = '$value, ';
    if (line.length + item.length > 79) {
      lines.add(line.toString().trimRight());
      line = StringBuffer('  ');
    }
    line.write(item);
  }
  lines.add(line.toString().trimRight());
  return lines.join('\n');
}
