/// Generates `lib/src/fonts/standard_metrics.g.dart` from the Adobe
/// core 14 AFM files (`vendor/adobe-core14`) and the Adobe Glyph List
/// (`vendor/adobe-agl`): for each standard font, its metrics, every glyph
/// (built-in code, name, width, Unicode) and its kerning pairs, as compact
/// strings the library parses on first use.
///
/// ```sh
/// dart run tool/generate_standard_fonts.dart
/// ```
library;

import 'dart:io';

void main() {
  final root = File(Platform.script.toFilePath()).parent.parent.path;
  final unicode = <String, String>{};
  for (final file in ['glyphlist.txt', 'zapfdingbats.txt']) {
    for (final line in File('$root/vendor/adobe-agl/$file').readAsLinesSync()) {
      if (line.startsWith('#') || !line.contains(';')) continue;
      final [name, codes] = line.split(';');
      // A name for several code points (a decomposition) keeps the first.
      unicode.putIfAbsent(name, () => codes.split(' ').first.toLowerCase());
    }
  }
  final fonts = [
    'Courier', 'Courier-Bold', 'Courier-Oblique', 'Courier-BoldOblique', //
    'Helvetica', 'Helvetica-Bold', 'Helvetica-Oblique',
    'Helvetica-BoldOblique', 'Times-Roman', 'Times-Bold', 'Times-Italic',
    'Times-BoldItalic', 'Symbol', 'ZapfDingbats',
  ];
  final out = StringBuffer()
    ..writeln('// GENERATED CODE - DO NOT MODIFY BY HAND.')
    ..writeln(
      '// Generated by `dart run tool/generate_standard_fonts.dart` from',
    )
    ..writeln('// the Adobe core 14 AFM files and the Adobe Glyph List; see')
    ..writeln('// vendor/adobe-core14/MustRead.html for their terms.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The metrics of the 14 standard fonts.')
    ..writeln('library;')
    ..writeln()
    ..writeln("import 'package:libpdf/src/fonts/standard_metrics.dart';")
    ..writeln()
    ..writeln('/// The standard fonts by name.')
    ..writeln('const Map<String, StandardFontData> standardFontData = {');
  for (final name in fonts) {
    final header = <String, String>{};
    String bboxAt(int index) => header['FontBBox']!.split(' ')[index];
    final glyphs = <String>[];
    final kerning = <String>[];
    for (final line in File(
      '$root/vendor/adobe-core14/$name.afm',
    ).readAsLinesSync()) {
      if (line.startsWith('C ')) {
        final fields = {
          for (final part in line.split(';'))
            if (part.trim().split(' ') case [final key, ...final rest])
              key: rest.join(' '),
        };
        final code = fields['C']!;
        final glyph = fields['N']!;
        final width = fields['WX']!;
        glyphs.add('$code $glyph $width ${unicode[glyph] ?? '-'}');
      } else if (line.startsWith('KPX ')) {
        final [_, left, right, value] = line.split(' ');
        kerning.add('$left $right $value');
      } else if (line.contains(' ')) {
        final space = line.indexOf(' ');
        header[line.substring(0, space)] = line.substring(space + 1).trim();
      }
    }
    final bbox = header['FontBBox']!.split(RegExp(r'\s+')).join(', ');
    out
      ..writeln("  '$name': StandardFontData(")
      ..writeln("    name: '$name',")
      ..writeln('    bbox: [$bbox],')
      ..writeln('    ascender: ${header['Ascender'] ?? bboxAt(3)},')
      ..writeln('    descender: ${header['Descender'] ?? bboxAt(1)},')
      ..writeln('    capHeight: ${header['CapHeight'] ?? bboxAt(3)},')
      ..writeln('    xHeight: ${header['XHeight'] ?? 0},')
      ..writeln('    italicAngle: ${header['ItalicAngle']},')
      ..writeln('    stemV: ${header['StdVW'] ?? 80},')
      ..writeln('    fixedPitch: ${header['IsFixedPitch'] == 'true'},')
      ..writeln('    symbolic: ${name == 'Symbol' || name == 'ZapfDingbats'},')
      ..writeln("    glyphs: '${glyphs.join(';')}',")
      ..writeln("    kerning: '${kerning.join(';')}',")
      ..writeln('  ),');
  }
  out.writeln('};');
  File('$root/lib/src/fonts/standard_metrics.g.dart')
      .writeAsStringSync(out.toString());
  stdout.writeln('generate_standard_fonts: ${fonts.length} fonts');
}
