/// Generates `lib/src/fonts/brotli_data.g.dart`: the data a Brotli
/// decoder needs (RFC 7932): the static dictionary (zlib-compressed, as it
/// is 122,784 bytes), the 121 word transforms and the context lookup
/// table, from the google/brotli sources at a pinned release (MIT
/// license). The dictionary is checked against the SHA-256 the RFC gives.
///
/// ```sh
/// dart run tool/generate_brotli.dart
/// ```
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:libpdf/libpdf.dart' show zlibEncode;

/// google/brotli v1.2.0.
const _commit = '028fb5a23661f123017c060daa546b55cf4bde29';

/// The dictionary's SHA-256, as RFC 7932 (appendix A) gives it.
const _dictionarySha256 =
    '20e42eb1b511c21806d4d227d07e5dd06877d8ce7b3a817f378f313653f35c70';

Future<Uint8List> _fetch(String path) async {
  final client = HttpClient();
  try {
    final request = await client.getUrl(
      Uri.parse(
        'https://raw.githubusercontent.com/google/brotli/$_commit/$path',
      ),
    );
    final response = await request.close();
    if (response.statusCode != 200) {
      throw StateError('$path: HTTP ${response.statusCode}');
    }
    final builder = BytesBuilder(copy: false);
    await response.forEach(builder.add);
    return builder.takeBytes();
  } finally {
    client.close();
  }
}

Future<void> main() async {
  final dictionary = await _fetch('c/common/dictionary.bin');
  if (_sha256(dictionary) != _dictionarySha256) {
    throw StateError("the dictionary is not RFC 7932's");
  }
  final transform = utf8.decode(await _fetch('c/common/transform.c'));
  final header = utf8.decode(await _fetch('c/common/transform.h'));
  final context = utf8.decode(await _fetch('c/common/context.c'));
  final license = utf8.decode(await _fetch('LICENSE')).trim();

  // The prefixes and suffixes: a C string of length-prefixed strings.
  final prefixSuffix = _cString(
    RegExp(r'kPrefixSuffix\[\d+\] =([\s\S]*?);').firstMatch(transform)![1]!,
  );
  final map = _numbers(
    RegExp(r'kPrefixSuffixMap\[\d+\] = \{([\s\S]*?)\};')
        .firstMatch(transform)![1]!,
  );
  final types = {
    for (final m in RegExp(
      r'BROTLI_TRANSFORM_(\w+) = (\d+)',
    ).allMatches(header))
      m[1]!: int.parse(m[2]!),
  };
  final triples = [
    for (final m in RegExp(r'(\d+), BROTLI_TRANSFORM_(\w+), (\d+)').allMatches(
      RegExp(r'kTransformsData\[\] = \{([\s\S]*?)\};')
          .firstMatch(transform)![1]!,
    ))
      (int.parse(m[1]!), types[m[2]!]!, int.parse(m[3]!)),
  ];
  if (triples.length != 121) {
    throw StateError('${triples.length} transforms, not 121');
  }
  List<int> affix(int id) {
    final at = map[id];
    return prefixSuffix.sublist(at + 1, at + 1 + prefixSuffix[at]);
  }

  final lookup = _numbers(
    RegExp(r'_kBrotliContextLookupTable\[2048\] = \{([\s\S]*?)\};')
        .firstMatch(context)![1]!
        .replaceAll(RegExp(r'/\*[\s\S]*?\*/'), ''),
  );
  if (lookup.length != 2048) throw StateError('context table');

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/generate_brotli.dart from google/brotli')
    ..writeln('// $_commit. Do not edit.')
    ..writeln('//')
    ..writeln("// The data is google/brotli's, under its license:")
    ..writeln('//');
  for (final line in const LineSplitter().convert(license)) {
    out.writeln('// $line'.trimRight());
  }
  out
    ..writeln()
    ..writeln('// The dictionary is one long string.')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln()
    ..writeln('/// The data of the Brotli decoder (RFC 7932).')
    ..writeln('library;')
    ..writeln()
    ..writeln('/// The static dictionary, zlib-compressed (122,784 bytes).')
    ..writeln(
      'const String brotliDictionaryZlib =\n'
      "    '${base64Encode(zlibEncode(dictionary, level: 9))}';",
    )
    ..writeln()
    ..writeln(
      '/// The word transforms: prefix, type (0 identity, 1-9 omit the last',
    )
    ..writeln(
      '/// 1-9 bytes, 10 uppercase the first letter, 11 all of them, 12-20',
    )
    ..writeln('/// omit the first 1-9 bytes), suffix.')
    ..writeln('const List<(List<int>, int, List<int>)> brotliTransforms = [');
  for (final (prefix, type, suffix) in triples) {
    out.writeln('  (${affix(prefix)}, $type, ${affix(suffix)}),');
  }
  out
    ..writeln('];')
    ..writeln()
    ..writeln(
      '/// The context lookup table: for each of the four context modes',
    )
    ..writeln(
      '/// (LSB6, MSB6, UTF8, signed), 256 entries for the last byte, then',
    )
    ..writeln('/// 256 for the one before.')
    ..writeln('const List<int> brotliContextLookup = [');
  for (var i = 0; i < lookup.length; i += 16) {
    out.writeln('  ${lookup.sublist(i, i + 16).join(', ')},');
  }
  out.writeln('];');
  const path = 'lib/src/fonts/brotli_data.g.dart';
  File(path).writeAsStringSync('$out');
  await Process.run(Platform.resolvedExecutable, ['format', path]);
  stdout.writeln('generate_brotli: wrote lib/src/fonts/brotli_data.g.dart');
}

/// The numbers in [text].
List<int> _numbers(String text) => [
  for (final m in RegExp(r'0x([0-9A-Fa-f]+)|\d+').allMatches(text))
    int.parse(m[1] ?? m[0]!, radix: m[1] == null ? 10 : 16),
];

/// The bytes of the concatenated C string literals in [text] (with a
/// trailing zero), comments left out.
List<int> _cString(String text) {
  final bytes = <int>[];
  final source = text.replaceAll(RegExp(r'/\*[\s\S]*?\*/'), '');
  for (final literal in RegExp(r'"((?:[^"\\]|\\.)*)"').allMatches(source)) {
    final s = literal[1]!;
    for (var i = 0; i < s.length; i++) {
      final c = s[i];
      if (c != r'\') {
        bytes.add(s.codeUnitAt(i));
        continue;
      }
      final next = s[++i];
      if (RegExp('[0-7]').hasMatch(next)) {
        final start = i;
        while (i - start < 2 &&
            i + 1 < s.length &&
            RegExp('[0-7]').hasMatch(s[i + 1])) {
          i++;
        }
        bytes.add(int.parse(s.substring(start, i + 1), radix: 8));
      } else if (next == 'x') {
        final start = i + 1;
        while (i + 1 < s.length && RegExp('[0-9a-fA-F]').hasMatch(s[i + 1])) {
          i++;
        }
        bytes.add(int.parse(s.substring(start, i + 1), radix: 16));
      } else {
        bytes.add(switch (next) {
          'n' => 10,
          't' => 9,
          'r' => 13,
          _ => next.codeUnitAt(0),
        });
      }
    }
  }
  return bytes..add(0);
}

/// SHA-256 of [data], in hexadecimal.
String _sha256(List<int> data) {
  const k = [
    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, //
    0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
    0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
    0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
    0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
    0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
    0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
    0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
    0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
    0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
    0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
  ];
  final padded = Uint8List(((data.length + 9 + 63) ~/ 64) * 64)
    ..setRange(0, data.length, data);
  padded[data.length] = 0x80;
  final view = ByteData.sublistView(padded)
    ..setUint32(padded.length - 8, (data.length * 8) ~/ 0x100000000)
    ..setUint32(padded.length - 4, (data.length * 8) & 0xffffffff);
  final h = [
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, //
    0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19,
  ];
  final w = Uint32List(64);
  int r(int x, int n) => ((x >> n) | (x << (32 - n))) & 0xffffffff;
  for (var b = 0; b < padded.length; b += 64) {
    for (var t = 0; t < 16; t++) {
      w[t] = view.getUint32(b + 4 * t);
    }
    for (var t = 16; t < 64; t++) {
      w[t] =
          (w[t - 16] +
              (r(w[t - 15], 7) ^ r(w[t - 15], 18) ^ (w[t - 15] >> 3)) +
              w[t - 7] +
              (r(w[t - 2], 17) ^ r(w[t - 2], 19) ^ (w[t - 2] >> 10))) &
          0xffffffff;
    }
    var [a, bb, c, d, e, f, g, hh] = h;
    for (var t = 0; t < 64; t++) {
      final t1 =
          (hh +
              (r(e, 6) ^ r(e, 11) ^ r(e, 25)) +
              ((e & f) ^ (~e & 0xffffffff & g)) +
              k[t] +
              w[t]) &
          0xffffffff;
      final t2 =
          ((r(a, 2) ^ r(a, 13) ^ r(a, 22)) + ((a & bb) ^ (a & c) ^ (bb & c))) &
          0xffffffff;
      hh = g;
      g = f;
      f = e;
      e = (d + t1) & 0xffffffff;
      d = c;
      c = bb;
      bb = a;
      a = (t1 + t2) & 0xffffffff;
    }
    for (final (i, v) in [a, bb, c, d, e, f, g, hh].indexed) {
      h[i] = (h[i] + v) & 0xffffffff;
    }
  }
  return [for (final v in h) v.toRadixString(16).padLeft(8, '0')].join();
}
